language: android
script: "./gradlew assembleDebug testDebug --info"
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository

before_install:
- export TZ=Europe/Prague
